server:
  port: 8081

spring:
  config:
    use-legacy-processing: true
  jpa:
    properties:
      hibernate:
        dialect:
      ddl-auto: update
  activemq:
#    broker-url: "tcp://localhost:61616"
    broker-url: "ssl://b-4c49c754-b8f9-4ec4-8fa7-7747d9b65a8f-1.mq.eu-west-1.amazonaws.com:61617"
    user: "admin"
    password: "modulshop-dev-test"
    packages:
      trust-all: "true"